[package]
name = "streamflow"
version = "0.0.1"
description = "StreamFlow"
authors = ["StreamFlow Devs <devs@streamflow.finance>"]
repository = "https://github.com/streamflow-finance/streamflow"
license = "AGPL-3"
edition = "2018"

[dependencies]
solana-program = "1.7.0"

[lib]
crate-type = ["cdylib", "lib"]
